services:
  movie-scrapers:
    container_name: movie_scrapers
    build:
        context: .
    ports:
      - "80:5000"
    environment:
      - IPINFO_API_KEY=your_actual_api_key_here
      - FLASK_APP=app.py
    networks:
      - npm-nw
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    restart: unless-stopped

networks:
  npm-nw:
    driver: bridge